# Server Configuration
server.port=8080

# Application Name
spring.application.name=web-utils

# Logging
logging.level.root=INFO
logging.level.com.common=DEBUG

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Seoul
